[package]
name = "apost3dview-render"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
apost3dview-core = { version = "0.1.0", path = "../core" }
bytemuck = { version = "1.25.2", features = ["derive"] }
egui = "0.36.1"
egui-wgpu = "0.36.1"
fontdue = "0.9.4"
glam = "0.33.3"
wgpu = "30.0.0"

[dev-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }
pollster = "1.0.1"
